spring:
  profiles:
    active: dev
---
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    properties:
      javax.persistence.validation.mode: none
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.show_sql: true
      hibernate.connection.characterEncoding: utf8mb4
      hibernate.connection.CharSet: utf8mb4
      hibernate.connection.useUnicode: true
      hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_second_level_cache: true
  flyway:
    enabled: true
    ignore-missing-migrations: true
    locations: classpath:/migration
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/jd2project_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: maxim
    password: root
    url: "jdbc:postgresql://localhost:5432/jd2project_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: org.postgresql.Driver
  profiles: dev

server:
  port: 8080
  servlet:
    context-path: /
---

amazon:
  images:
    s3: finalprojectjd2maximzabavskiy
    accessKeyId: AKIAINQWSUAH5APHUMAQ
    secretKey: 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
    bucket: finalprojectjd2maximzabavskiy
    serverUrl: "https://finalprojectjd2maximzabavskiy.s3.eu-central-1.amazonaws.com"
    userFolder: users
    region: eu-central-1

---

jwtconfig:
  secret: secret
  expiration: 60000

---
spring:
  jpa:
    properties:
      javax.persistence.validation.mode: none
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.show_sql: true
      hibernate.connection.characterEncoding: utf8mb4
      hibernate.connection.CharSet: utf8mb4
      hibernate.connection.useUnicode: true
      hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_second_level_cache: true
  flyway:
    enabled: false
    ignore-missing-migrations: true
    locations: classpath:/migration
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/admin_spring?useUnicode=yes&characterEncoding=UTF-8
      maximum-pool-size: 10
      driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin_spring
    password: 12345
    url: jdbc:mysql://localhost:3306/admin_spring?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles: prod

server:
  port: 8888
  servlet:
    context-path: /spring


